[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'sheerun/vim-polyglot'
hook_add = '''
let g:polyglot_disabled = ['markdown', 'tsx', 'typescript', 'csv']
'''

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'

[[plugins]]
repo = 'thinca/vim-ft-diff_fold'

[[plugins]]
repo = 'thinca/vim-ft-help_fold'

[[plugins]]
repo = 'vim-jp/autofmt'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'rcmdnk/vim-markdown'

[[plugins]]
repo = 'JesseKPhillips/d.vim'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'Shirk/vim-gas'

[[plugins]]
repo = 'chrisbra/vim-zsh'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'

# [[plugins]]
# repo = 'Shougo/deoppet.nvim'

[[plugins]]
repo = 'tbodt/deoplete-tabnine'
build = './install.sh'


##############################################################################
#
#  Additional pluggins
#
##############################################################################
[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'luochen1990/rainbow'

[[plugins]]
repo  = 'vim-airline/vim-airline'

[[plugins]]
repo = 'huawenyu/neogdb.vim'

[[plugins]]
repo = 'dylanaraps/wal.vim'
hook_source = '''
  colorscheme wal
'''
